server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dan1el71/tickets-config-server
          skip-ssl-validation: true
          username: Dan1el71
          password: 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
          search-paths: configurations
        bootstrap: true