server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dan1el71/tickets-config-server
          skip-ssl-validation: true
          username: -
          password: -
          search-paths: configurations
        bootstrap: true
